# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: PILL.PILL
PackageVersion: 0.1.0

ReleaseDate: 2026-09-29

Installers:
  - Architecture: x64
    Scope: user
    InstallerType: nullsoft
    InstallerUrl: https://github.com/AmoghxAnubis/PILL/releases/download/v0.1.0/PILL_0.1.0_x64-setup.exe
    InstallerSha256: C2E114A3EDF5438C3A7BD90C1680534397268F6D7D0EEDB3CB7D72DE6C649D54
    InstallerSwitches:
      Silent: /S
    AppsAndFeaturesEntries:
      - DisplayName: PILL
        Publisher: PILL

ManifestType: installer
ManifestVersion: 1.28.0
